### ISSUE TITLE
Signal description of the AXI4-Lite 

### ISSUE THREAD

**Issue by mahadevaswamy05** [mbits-mirafra/axi4_avip#103]
Here we are exploring each signal of the axi4 lite- like which signal we are using and which we're going to implement.

**Comment by mahadevaswamy05** [comment]
You can see the below picture for signal list of the axi4 lite

<img width="524" alt="image" src="https://github.com/mbits-mirafra/axi4_avip/assets/106074838/57582511-4993-4cb8-b302-cc076bbdea0b">

**Comment by mahadevaswamy05** [comment]
**Global signals axi4 protocol**  
 **ACLK**: - Each AXI component uses a single clock signal, ACLK. All input signals are sampled on the rising edge of ACLK. 
All output signal changes must occur after the rising edge of ACLK.
**ARESETn**: -  The AXI protocol uses a single active LOW reset signal, ARESETn. The reset signal can be asserted 
asynchronously, but de-assertion must be synchronous with a rising edge of ACLK.
___

**Write address channel signals**

**AWADDR**:-  Write address, The write address gives the address of the first transfer in a write burst transaction
**AWPROT**:-  Protection type, This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access. 
**AWVALID**: -  Write address valid, This signal indicates that the channel is signaling valid write address and control information. 
**AWREADY**: - Write address ready, This signal indicates that the slave is ready to accept an address and associated control signals.

___

**Write data channel signals**

 **WDATA**: - Master Write data.
 **WSTRB**: - Write strobes. This signal indicates which byte lanes hold valid data. There is one write strobe bit for each eight bits of the write data bus.
**WVALID**: - Write valid. Indicates that the write data and write strobes are valid
**WREADY**: - Write Ready. Indicates that the slave is ready to accept the write data. 

___
**Write response channel signals**

**BRESP** :-  Write response. This signal indicates the status of the write transaction.
**BVALID** :-  Write response valid. This signal indicates that the channel is signalling a valid write response.
**BREADY** : - Response ready. This signal indicates that the master can accept a write response.

___

**Read address channel signals**

**ARADDR**:-  Read address. The read address gives the address of the first transfer in a read burst transaction.
**ARPROT**:-  Protection type, This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access.  
**ARVALID**: -  Read address valid, This signal indicates that the channel is signalling valid read address and control information. 
**ARREADY**: - Read address ready, This signal indicates that the slave is ready to accept an address and associated control signals

___
**Read data channel signals**

 **RDATA**: - Read data Carries the read data from the slave to the master
**RVALID**: - Read valid. Indicates that the read data and response information are valid
**RREADY**: -Read Ready. Indicates that the master is ready to accept the read data and response information
**RRESP**: - Read response. It Indicates the status of the read transaction. The possible values and their meanings are  

                     00 (OKAY): Read transaction completed successfully.
                     01 (EXOKAY): Exclusive access okay (not used in AXI4-Lite).
                     10 (SLVERR): Slave error, indicating the slave encountered an error processing the read.
                     11 (DECERR): Decode error, indicating the address did not match any valid slave address range.

**Comment by muneebullashariff** [comment]
There is no RSTRB, it should be Ready response.
