### ISSUE TITLE
Signal description of the AXI4-Basic 

### ISSUE THREAD

**Issue by mahadevaswamy05** [mbits-mirafra/axi4_avip#104]
Here we are exploring each signal of the axi4 Basic -like which signal we are using and which we're going to implement.

**Comment by mahadevaswamy05** [comment]
**Global signals axi4 protocol**  
 **ACLK**: - Each AXI component uses a single clock signal, ACLK. All input signals are sampled on the rising edge of ACLK. 
All output signal changes must occur after the rising edge of ACLK.
**ARESETn**: -  The AXI protocol uses a single active LOW reset signal, ARESETn. The reset signal can be asserted 
asynchronously, but de-assertion must be synchronous with a rising edge of ACLK.
___

**Write address channel signals**

**AWADDR**:-  Write address, The write address gives the address of the first transfer in a write burst transaction
**AWID**:-  Write address ID. This signal is the identification tag for the write address group of signals. 
**AWLEN**:- Burst length. The burst length gives the exact number of transfers in a burst. This information determines the number of data transfers associated with the address. 
**AWSIZE**:-  Burst size. This signal indicates the size of each transfer in the burst.
 **AWBURST**:- Burst type. The burst type and the size information, determine how the address for each transfer within the burst is calculated.
**AWPROT**:-  Protection type, This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or instruction access. 
**AWVALID**: -  Write address valid, This signal indicates that the channel is signaling valid write address and control information. 
**AWREADY**: - Write address ready, This signal indicates that the slave is ready to accept an address and associated control signals.

___

**Write data channel signals**

**WDATA**: - Master Write data.
**WID**:- Master Write ID tag. This signal is the ID tag of the write data transfer. _Supported only in AXI3._
**WSTRB**: - Write strobes. This signal indicates which byte lanes hold valid data. There is one write strobe bit for each eight bits of the write data bus.
**WLAST**:- Write last. This signal indicates the last transfer in a write burst.
**WVALID**: - Write valid. This signal indicates that valid write data and strobes are available.
**WREADY**: - Write valid. This signal indicates that valid write data and strobes are available.

___
**Write response channel signals**

**BRESP** :-  Write response. This signal indicates the status of the write transaction.
**BID**:- Response ID tag. This signal is the ID tag of the written response
**BVALID** :-  Write response valid. This signal indicates that the channel is signaling a valid write response.
**BREADY** : - Response ready. This signal indicates that the master can accept a write response.

___

**Read address channel signals**

**ARADDR**:-  Read address. The read address gives the address of the first transfer in a read burst transaction.
**ARID**:-  Read address ID. This signal is the identification tag for the read address group of signals. 
**ARLEN**:- Burst length. The burst length gives the exact number of transfers in a burst. This information determines the number of data transfers associated with the address. 
**ARSIZE**:-  Burst size. This signal indicates the size of each transfer in the burst.
 **ARBURST**:- Burst type. The burst type and the size information, determine how the address for each transfer within the burst is calculated.
**ARPROT**:-  Protection type, This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access.  
**ARVALID**: -  Read address valid, This signal indicates that the channel is signaling valid read address and control information. 
**ARREADY**: - Read address ready, This signal indicates that the slave is ready to accept an address and associated control signals

___
**Read data channel signals**

**RDATA**: - Master Read data.
**RID**:- Master Read ID tag. This signal is the ID tag of the read data transfer. _Supported only in AXI3._
**RRESP**:- Read response. This signal indicates the status of the read transfer.
**RLAST**:- Read last. This signal indicates the last transfer in a read burst.
**RVALID**: - Read valid. This signal indicates that valid read data and strobes are available.
**RREADY**: - Read valid. This signal indicates that valid read data and strobes are available.

**Comment by muneebullashariff** [comment]
No read strobes for read channel. Only available for write data.
