### ISSUE TITLE
Read the documentation to understand more about the usage

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/axi4_avip#24]
- [x] #37
- [x] #38
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [ ] #84

**Comment by muneebullashariff** [comment]
Document the learnings
https://docs.svunit.org/en/latest/

**Comment by Gopalsuthar2308** [comment]
**Question**
In document under writing unit test/interacting with the UUT they wrote example and note i mentioned below,

For example, if the state of the oPin and oBus outputs is conditional based on the state of the iPin, oPin and oBus can be verified by driving iPin as necessary:

```
`SVTEST(test0)
  iPin = 1;
  #0 `FAIL_IF(oPin !== 1)
`SVTEST_END

`SVTEST(test1)
  helper();
  #0 `FAIL_UNLESS_EQUAL(oBus, 'h6)
`SVTEST_END

function helper();
  iPin = 1;
endfunction
```

> Note
> The addition of the #0 assumes oPin and oBus are asynchronous outputs that require a delta cycle be consumed before they reach their intended state.

so, here my question what is delta cycle and why they are using #0

**Comment by Gopalsuthar2308** [comment]
- Here link of svUnit Document: https://docs.svunit.org/en/latest/

- In the above link different categories is there, you can track by the different task just follow the below link for the more clarity,

https://github.com/mbits-mirafra/axi4_avip/issues/24#issue-1942670956
