### ISSUE TITLE
How to run regression

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/axi4_avip#54]
Inside testrunner if we have multiple testsuite and if we run using `runSVUnit -s questa` command then it will run all unit test template inside all testsuite.

**Comment by Gopalsuthar2308** [comment]
**Diagram:**
<img width="775" alt="structure" src="https://github.com/mbits-mirafra/axi4_avip/assets/110448382/16dc5a32-29cb-4c1f-bce4-21a08c9fd3b2">

- see in the below figure, inside testrunner1 i created two directory one is testsuite_1_test and second is testsuite_multi_test , testsuite_1_test have one UUT and unit test template and testsuite_multi_test have two UUT and unit test template.

![image](https://github.com/mbits-mirafra/axi4_avip/assets/110448382/2315ed3f-4408-4878-a99c-d34d822561ac)

- use `runSVUnit -s queta` command and run inside testrunner, it will generate run.log and compile.log file.
- open run.log file and check output of all unit test template.

**run command:**

![image](https://github.com/mbits-mirafra/axi4_avip/assets/110448382/ede10436-d81c-47a4-8295-2c59fddff02f)

**Output:**

<img width="948" alt="Untitled" src="https://github.com/mbits-mirafra/axi4_avip/assets/110448382/f2e18179-975f-4856-a7df-a39dd8a755ee">
<img width="948" alt="untitled2" src="https://github.com/mbits-mirafra/axi4_avip/assets/110448382/a7a3a39c-dad5-4ba4-974e-979fa0bc2b8c">
<img width="948" alt="Untitled3" src="https://github.com/mbits-mirafra/axi4_avip/assets/110448382/a29b81d2-c621-4744-9837-63e0d22d4dd2">

**Comment by muneebullashariff** [comment]
@Gopalsuthar2308 How do we assign the testrunner? And can we have multiple testrunners?

We can choose which folder to run as a testrunner, refer this comment:
https://github.com/mbits-mirafra/axi4_avip/issues/46#issuecomment-1784528982

We can refer the below for more information on testrunners:
- #84
