### ISSUE TITLE
Best practices for naming the unit tests

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/axi4_avip#56]

**Comment by mahadevaswamy05** [comment]
**1. CamelCase:-** The use of capital letters to begin the second word in a phrase, when it is not separated from the first word by a space.

- ThisIsCamelCase
- thisIsAlsoCamelCase
- THIS_IS_NOT_CAMEL_CASE
- neither-is-this

**2. PascalCase:-** The first letter must have an upper case.
- ThisIsPascalCase
- thisIsNotPascalCase 

**3. snack case:**- Each word is in lower case and separated by underscores. 
- sanke_case_example 

**4. kebab case:-** Each word is in lowercase and separated by dashes. 
- kebab-case-example

Don't do this:-
- -computerMethod
- computerVariable-

**5. WikiCase:-** Uppercase letter followed by a lowercase one. 
- VariableNameExamples

**Comment by muneebullashariff** [comment]
- The above mentioned points are the staring place. However, please follow the below guidelines:
 #40

**Comment by muneebullashariff** [comment]
Naming of tests should follow the below format:

Given_When_Then
Given_ReadWriteInlineConstraint_When_Write_Expect_ValueZero

For more reference:
https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea
