### ISSUE TITLE
Example as how to generate waveforms using the eda playground

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/axi4_avip#97]

**Comment by Gopalsuthar2308** [comment]
Here I have **apb_slave** example code.

Follow the below link to understand about apb_slave example,
- https://github.com/mbits-mirafra/axi4_avip/issues/63

Add **dumpvars** and **wlfdumpvars** in unit test.

```systemverilog
initial begin
    $dumpvars(1,apb_slave_unit_test); //apb_slave_unit_test name is module name
    $wlfdumpvars(0);
end
```

And Select open EPWave after run option,

<img width="960" alt="apbslave" src="https://github.com/mbits-mirafra/axi4_avip/assets/110448382/c43840ab-34d3-4133-9e21-d5af59a9f492">


**Waveforms:**

![image](https://github.com/mbits-mirafra/axi4_avip/assets/110448382/498d9448-a675-456a-bc7e-45a5172e094a)


For Full code Follow below EDA Playground Link,

- https://www.edaplayground.com/x/9wG9
