### ISSUE TITLE
Features of AXI4_Basic

### ISSUE THREAD

**Issue by Gopalsuthar2308** [mbits-mirafra/axi4_avip#98]
Here we'll explore all the features of the axi4-basics and inheriting some features from the axi4-lite and what we are implementing and all the other features we are covering here.

**Comment by mahadevaswamy05** [comment]
1. Simple Handshaking Mechanism using the valid and ready signal.
(using the valid and ready signal we need to think about the across the channels)
2. Blocking and nonblocking Transfers
3. Outstanding transfer:- Master can issue multiple transactions without waiting for the earlier transaction to complete
(How many outstanding transfers will be supported depends on the Memory and address)
4. Parallel write and read transfer.
5. Parallel connecting between the Address channel and Data channel.
6. Data can be sent before an Address and during the Address, or Maybe a little later than the Address.
7. ID’s concepts will be there, like multiple transaction   
  i. Out-of-order transactions,  
  ii. In order transactions

8. Burst-based transactions with only start address issued.
9. Narrow transfer it will support.
10.  Unaligned transfer it will support.
11. No strict timing relationship between the address and the data channel which means a master could issue a write address on the write address channel, but there is no time requirement for when the master has to provide the corresponding data to write on the written data channel.
13.
