### ISSUE TITLE
EDA Playground Experiment

### ISSUE THREAD

**Issue by Gopalsuthar2308** [mbits-mirafra/axi4_avip#99]
Here we will give an example for any basic unit test code and we'll give an EDA Playground link, So if people can use this link and modify the code, So it will generate a new link or not.

- [x] #100

**Comment by mahadevaswamy05** [comment]
https://edaplayground.com/x/9n7a  

In this link original code will be there and This code is saved by using the public (Anyone with a link can view), Just see the below picture. 
   
<img width="722" alt="image" src="https://github.com/mbits-mirafra/axi4_avip/assets/106074838/42177fd3-d13a-4eb9-9488-403012e02501">

Now I'll open this link it will show the original code on the eda playground like the below picture.

<img width="804" alt="image" src="https://github.com/mbits-mirafra/axi4_avip/assets/106074838/e2effa0b-00cf-48c8-baa7-1e4a28c66730">

---

**Comment by mahadevaswamy05** [comment]
Now their copy option is there So if you click on copy it will copy this code and it will create a new link for this code on our local EDA playground then you can modify this code. 

When I modify the above code and save it, then it will save it in our local EDA playground.
And See the below picture.

<img width="827" alt="image" src="https://github.com/mbits-mirafra/axi4_avip/assets/106074838/f4caf09c-af80-47b4-8600-3d7292ca0ca7">
